const skills = [
    "Java",
    "JavaScript",
    "HTML",
    "CSS",
    "Bootstrap",
    "PHP",
    "SQL",
    "Node.js",
    "Express.js",
    "MongoDB",
    "React",
    "Git",
    "GitHub",
    "Docker",
    "AWS",
    "Rest API",
    "C#",
    "C++",
    "Tailwind",
    "Kubernetes",
    "Data Structures and Algorithms",
    "Kotlin",
    "DSA",
    "Go",
    "Python",
    "C",
    "Rust",
    "Swift",
    "Dart",
    "Scala",
    "Pearl",
    "Ruby",
    "R",
    "MATLAB",
    "Julia",
    "TypeScript",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "jQuery",
    "Material UI",
    "Chakra UI",
    "Sass",
    "Less",
    "Flask",
    "FastAPI",
    "Laravel",
    "ASP.NET",
    "Ruby on Rails",
    "NestJS",
    "Koa",
    "Hapi",
    "Gin",
    "Fiber",
    "PostgreSQL",
    "MariaDB",
    "SQLite",
    "Oracle",
    "SQL Server",
    "Cassandra",
    "Redis",
    "DynamoDB",
    "Neo4j",
    "Firebase",
    "Supabase",
    "AWS",
    "GCP",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "Terraform",
    "Ansible",
    "Helm",
    "Nginx",
    "Apache",
    "Prometheus",
    "Grafana",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "OpenCV",
    "Hugging Face",
    "LangChain",
    "XGBoost",
    "Keras",
    "NLP",
    "Computer Vision",
    "Android",
    "iOS",
    "Flutter",
    "React Native",
    "Xamarin",
    "IntelliJ IDEA",
    "Yarn",
    "GraphQL",
    "Microservices",
    "OOP",
    "DSA",
    "Agile",
    "Scrum",
    "CI/CD",
    "MVC",
    "WebSockets",
    "TDD",
    "Eclipse",
    "Maven",
    "Figma",
    "Jira",
    "Trello",
    "Postman",
];

module.exports = skills;